baseURL = "https://gcr-solutions.github.io/quantum-computing-for-life-science-workshop/"
languageCode = "en-us"
title = "Quantum Computing Solution"
theme = "hugo-theme-learn"
contentDir = "../docs"
canonifyURLs = true
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[params]
  disableLandingPageButton = true
